# Generated by Django 3.0.3 on 2020-03-17 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Serialized',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serialnumber', models.CharField(max_length=20)),
                ('dateaquired', models.DateField(auto_now_add=True)),
                ('datedeposed', models.DateField(blank=True)),
                ('ordernumber', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name': 'Serialized',
                'verbose_name_plural': 'Serializeds',
            },
        ),
    ]
