# Generated by Django 3.0.3 on 2020-04-02 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Serialized',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serialnumber', models.CharField(default='none', max_length=20)),
                ('gunmasterid', models.CharField(blank=True, max_length=50)),
                ('modeltype', models.CharField(default='AR15', max_length=50)),
                ('color', models.CharField(default='BLK', max_length=50)),
                ('dateaquired', models.CharField(default='01-01-2020', max_length=15)),
                ('datedeposed', models.CharField(default='01-01-2020', max_length=15)),
                ('ininventory', models.BooleanField(default=True)),
                ('ordernumber', models.CharField(blank=True, default='0000', max_length=50)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
    ]
