# Generated by Django 3.0.3 on 2020-03-17 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serialized', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='serialized',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
