# Generated by Django 3.0.3 on 2020-04-02 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serialized', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serialized',
            name='color',
            field=models.CharField(default='BLK', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='serialized',
            name='dateaquired',
            field=models.CharField(default='01-01-2020', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='serialized',
            name='datedeposed',
            field=models.CharField(default='01-01-2020', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='serialized',
            name='gunmasterid',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='serialized',
            name='ininventory',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='serialized',
            name='modeltype',
            field=models.CharField(default='AR15', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='serialized',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='serialized',
            name='ordernumber',
            field=models.CharField(blank=True, default='0000', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='serialized',
            name='serialnumber',
            field=models.CharField(default='none', max_length=20, null=True),
        ),
    ]
