# Generated by Django 3.0.3 on 2020-03-19 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serialized', '0002_serialized_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='serialized',
            name='ininventory',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='serialized',
            name='dateaquired',
            field=models.DateField(),
        ),
    ]
