# Generated by Django 3.0.3 on 2020-03-24 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serialized', '0003_auto_20200319_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='serialized',
            name='color',
            field=models.CharField(choices=[('BLK', 'BLK'), ('FDE', 'FDE'), ('STEALTH', 'STEALTH'), ('OD', 'OD'), ('RIFLE', 'RIFLE'), ('CLEAR', 'CLEAR'), ('PINK', 'PINK')], default='BLK', max_length=50),
        ),
        migrations.AddField(
            model_name='serialized',
            name='modeltype',
            field=models.CharField(choices=[('AR15', 'AR15'), ('AR308', 'AR308'), ('TAC9', 'TAC9')], default='AR15', max_length=50),
        ),
        migrations.AlterField(
            model_name='serialized',
            name='dateaquired',
            field=models.DateField(auto_now_add=True),
        ),
    ]
