# Generated by Django 3.0.3 on 2020-04-20 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serialized', '0003_auto_20200420_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serialized',
            name='gunmasterid',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
