# Generated by Django 3.0.3 on 2020-03-26 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serialized', '0004_auto_20200324_1524'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serialized',
            options={},
        ),
    ]
