# Generated by Django 3.0.3 on 2020-03-30 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serialized', '0005_auto_20200326_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serialized',
            name='modeltype',
            field=models.CharField(choices=[('TNARMS15', 'TNARMS15'), ('AR308', 'AR308'), ('TAC9', 'TAC9')], default='AR15', max_length=50),
        ),
        migrations.AlterField(
            model_name='serialized',
            name='serialnumber',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
