# Generated by Django 3.0.3 on 2020-03-30 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serialized', '0006_auto_20200330_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serialized',
            name='datedeposed',
            field=models.DateField(blank=True, default='1775/11/10'),
        ),
        migrations.AlterField(
            model_name='serialized',
            name='ordernumber',
            field=models.CharField(blank=True, default='0000', max_length=50),
        ),
    ]
