@ACCESS_TOKEN = 993u0lwo671cywg6oxuuhn53elkw28p
@CLIENT_ID = 5zu8djlu07xick65yf3vgs3urf6oxm1
@STORE_HASH = e6d39bb59d02e87f66844799d28949d1fee712c7d18ca32daaa3f3dcd5c4c2cb


GET https://api.bigcommerce.com/stores/{{STORE_HASH}}/v2/orders/{id}/transactions
X-Auth-Token: {{ACCESS_TOKEN}}
X-Auth-Client: {{CLIENT_ID}}
Content-Type: application/json
Accept: application/json