# Generated by Django 3.0.3 on 2020-04-08 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0002_auto_20200406_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerorder',
            name='customernotes',
            field=models.TextField(blank=True, verbose_name='Customer Notes'),
        ),
        migrations.AddField(
            model_name='customerorder',
            name='staffnotes',
            field=models.TextField(blank=True, verbose_name='Staff Notes'),
        ),
    ]
