# Generated by Django 3.0.3 on 2020-04-08 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0003_auto_20200408_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerorder',
            name='orderdate',
            field=models.CharField(max_length=200, verbose_name='Order Date and Time'),
        ),
    ]
