# Generated by Django 3.0.3 on 2020-04-08 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0005_auto_20200408_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerorder',
            name='shippingaddress',
            field=models.TextField(verbose_name='Shipping Address'),
        ),
    ]
