# Generated by Django 3.0.3 on 2020-04-08 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0006_auto_20200408_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerorder',
            name='billingaddress',
            field=models.TextField(verbose_name='Billing Address'),
        ),
    ]
