# Generated by Django 2.2.10 on 2020-02-26 22:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typemodel', models.CharField(choices=[('AR15', 'AR15'), ('AR308', 'AR308'), ('TAC9', 'TAC9'), ('80', '80')], max_length=50)),
                ('color', models.CharField(choices=[('BLK', 'BLK'), ('FDE', 'FDE'), ('STEALTH', 'STEALTH'), ('OD', 'OD'), ('RIFLE', 'RIFLE'), ('CLEAR', 'CLEAR')], max_length=50)),
                ('instock', models.PositiveIntegerField()),
                ('blem', models.BooleanField(default=False)),
                ('slug', models.SlugField(blank=True, default=uuid.uuid1, editable=False, unique=True)),
            ],
        ),
    ]
