# Generated by Django 2.2.10 on 2020-02-26 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='slug',
        ),
    ]
