# Generated by Django 3.0.3 on 2020-06-10 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='typemodel',
            field=models.CharField(choices=[('AR15', 'AR15'), ('AR308', 'AR308'), ('TAC9', 'TAC9'), ('80', '80'), ('JIGS', 'JIGS'), ('BRASS', 'BRASS'), ('LPK15', 'LPK15'), ('LPK308', 'LPK308'), ('TAC9ARM', 'TAC9ARM'), ('TAC9BUT', 'TAC9BUT'), ('TAC9EJT', 'TAC9EJT'), ('SERNUM', 'SERNUM')], default='80', max_length=50),
        ),
    ]
