# Generated by Django 3.0.3 on 2020-03-26 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20200326_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumables',
            name='updatedby',
            field=models.CharField(default='Amy', help_text='Example: Amy on xx/xx', max_length=30),
        ),
        migrations.AddField(
            model_name='supplier',
            name='updatedby',
            field=models.CharField(default='Amy', help_text='Example: Amy on xx/xx', max_length=30),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='updatedby',
            field=models.CharField(default='Amy', help_text='Example: Amy on xx/xx', max_length=30),
        ),
    ]
