# Generated by Django 3.0.3 on 2020-06-10 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20200610_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='notes',
            field=models.TextField(default='none'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='color',
            field=models.CharField(choices=[('BLK', 'BLK'), ('FDE', 'FDE'), ('STEALTH', 'STEALTH'), ('OD', 'OD'), ('RIFLE', 'RIFLE'), ('CLEAR', 'CLEAR'), ('PINK', 'PINK'), ('Other', 'Other')], default='BLK', max_length=50),
        ),
    ]
