# Generated by Django 3.0.3 on 2020-03-26 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20200326_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='updatedby',
            field=models.CharField(blank=True, default='Amy', help_text='Example: Amy on xx/xx', max_length=30),
        ),
    ]
