# Generated by Django 3.0.3 on 2020-06-12 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20200610_1538'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('ar15blk', models.IntegerField(default=0)),
                ('ar15fde', models.IntegerField(default=0)),
                ('ar15od', models.IntegerField(default=0)),
                ('ar15rifle', models.IntegerField(default=0)),
                ('ar15stealth', models.IntegerField(default=0)),
                ('ar15pink', models.IntegerField(default=0)),
                ('ar15clear', models.IntegerField(default=0)),
            ],
        ),
    ]
