# Generated by Django 3.0.3 on 2020-03-26 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_auto_20200326_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='updatedby',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
