# Generated by Django 3.0.3 on 2020-03-04 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_auto_20200303_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='purchase_order_num',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
