# Generated by Django 3.0.3 on 2020-03-04 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_orders_purchase_order_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumables',
            name='AR308kit',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='consumables',
            name='ar15kit',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='consumables',
            name='tac9ejector',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='consumables',
            name='bigbrass',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='consumables',
            name='littlebrass',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='consumables',
            name='sernum',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='consumables',
            name='tac9arm',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
