# Generated by Django 3.0.3 on 2020-03-04 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_auto_20200304_1019'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consumables',
            old_name='sernum',
            new_name='serialnum',
        ),
        migrations.AddField(
            model_name='consumables',
            name='drillbits',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='consumables',
            name='jigs',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='consumables',
            name='jigscrew',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='consumables',
            name='pistolgripscrew',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
