# Generated by Django 3.0.3 on 2020-03-26 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_remove_inventory_updatedby'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='updatedby',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
