# Generated by Django 3.0.3 on 2020-03-26 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_inventory_updatedby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='updatedby',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
