# Generated by Django 3.0.3 on 2020-03-04 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_auto_20200304_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumables',
            name='consumablesnotes',
            field=models.TextField(blank=True),
        ),
    ]
