# Generated by Django 3.0.3 on 2020-07-22 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_availableinventory_fde80'),
    ]

    operations = [
        migrations.AddField(
            model_name='availableinventory',
            name='jig80',
            field=models.CharField(default='00/00', max_length=50),
        ),
    ]
