# Generated by Django 3.0.3 on 2020-03-06 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_consumables_consumablesnotes'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumables',
            name='AR15_Buffer_Assembly',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='consumables',
            name='AR308_Buffer_Assembly',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
