# Generated by Django 3.0.3 on 2020-09-24 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_auto_20200924_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='blemblk3080',
            field=models.CharField(default=0, max_length=50, verbose_name='Blem Black AR3080'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='blemblk980',
            field=models.CharField(default=0, max_length=50, verbose_name='Blem Blk TAC-980'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='blemfde3080',
            field=models.CharField(default=0, max_length=50, verbose_name='Blem FDE AR3080'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='blemfde980',
            field=models.CharField(default=0, max_length=50, verbose_name='Blem FDE TAC-980'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='blemod3080',
            field=models.CharField(default=0, max_length=50, verbose_name='Blem OD AR3080'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='blemod980',
            field=models.CharField(default=0, max_length=50, verbose_name='Blem OD TAC-980'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='blemrif3080',
            field=models.CharField(default=0, max_length=50, verbose_name='Blem Rifle AR3080'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='blemrif980',
            field=models.CharField(default=0, max_length=50, verbose_name='Blem Rifle TAC-980'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='blemstl3080',
            field=models.CharField(default=0, max_length=50, verbose_name='Blem Stealth AR3080'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='blemstl980',
            field=models.CharField(default=0, max_length=50, verbose_name='Blem Stealth TAC-980'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='blk3080',
            field=models.CharField(default=0, max_length=50, verbose_name='Black AR3080'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='blk980',
            field=models.CharField(default=0, max_length=50, verbose_name='Black TAC-980'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='fde3080',
            field=models.CharField(default=0, max_length=50, verbose_name='FDE AR3080'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='fde980',
            field=models.CharField(default=0, max_length=50, verbose_name='FDE TAC980'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='od3080',
            field=models.CharField(default=0, max_length=50, verbose_name='OD Ar3080'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='od980',
            field=models.CharField(default=0, max_length=50, verbose_name='OD TAC-980'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='rif3080',
            field=models.CharField(default=0, max_length=50, verbose_name='Rifle AR3080'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='rif980',
            field=models.CharField(default=0, max_length=50, verbose_name='Rifle TAC-980'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='stl3080',
            field=models.CharField(default=0, max_length=50, verbose_name='Stealth AR3080'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='stl980',
            field=models.CharField(default=0, max_length=50, verbose_name='Stealth TAC-980'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='blemrifle80',
            field=models.CharField(default=0, max_length=50, verbose_name='Blem Rifle 80'),
        ),
    ]
