# Generated by Django 3.0.3 on 2020-03-10 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_auto_20200306_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='color',
            field=models.CharField(choices=[('BLK', 'BLK'), ('FDE', 'FDE'), ('STEALTH', 'STEALTH'), ('OD', 'OD'), ('RIFLE', 'RIFLE'), ('CLEAR', 'CLEAR'), ('PINK', 'PINK')], max_length=50),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='instock',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='orders',
            name='color',
            field=models.CharField(choices=[('BLK', 'BLK'), ('FDE', 'FDE'), ('STEALTH', 'STEALTH'), ('OD', 'OD'), ('RIFLE', 'RIFLE'), ('CLEAR', 'CLEAR'), ('PINK', 'PINK')], default='BLK', max_length=50),
        ),
    ]
