# Generated by Django 3.0.3 on 2020-03-10 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_auto_20200310_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='instock',
            field=models.CharField(max_length=20),
        ),
    ]
