# Generated by Django 3.0.3 on 2020-03-26 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_inventory_updatedby'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='updatedby',
        ),
    ]
