# Generated by Django 3.0.3 on 2020-09-24 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_auto_20200924_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumables',
            name='bubble9',
            field=models.CharField(default=0, max_length=10, verbose_name='TAC9 Bubble Tube'),
        ),
        migrations.AddField(
            model_name='consumables',
            name='pb15',
            field=models.CharField(default=0, max_length=10, verbose_name='AR15 Pistol Buffer'),
        ),
        migrations.AddField(
            model_name='consumables',
            name='pb9',
            field=models.CharField(default=0, max_length=10, verbose_name='TAC9 Pistol Buffer'),
        ),
        migrations.AddField(
            model_name='consumables',
            name='sb15',
            field=models.CharField(default=0, max_length=10, verbose_name='AR15 Sb Tactical Assembly'),
        ),
        migrations.AddField(
            model_name='consumables',
            name='sb9',
            field=models.CharField(default=0, max_length=10, verbose_name='TAC9 SB Tactical Assembly'),
        ),
        migrations.AddField(
            model_name='consumables',
            name='shock15',
            field=models.CharField(default=0, max_length=10, verbose_name='AR15 Shockwave Pistol Assembly'),
        ),
        migrations.AddField(
            model_name='consumables',
            name='shock9',
            field=models.CharField(default=0, max_length=10, verbose_name='TAC9 Shockwave Assembly'),
        ),
        migrations.AlterField(
            model_name='consumables',
            name='AR308_Buffer_Assembly',
            field=models.CharField(default=0, max_length=10, verbose_name='AR308 Rifle Buffer'),
        ),
    ]
