# Generated by Django 3.0.3 on 2020-03-30 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_remove_inventory_updatedby'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consumables',
            name='updatedby',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='updatedby',
        ),
    ]
