# Generated by Django 3.0.3 on 2020-09-24 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_auto_20200924_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumables',
            name='jig308',
            field=models.CharField(default=0, max_length=10, verbose_name='AR3080 Jig'),
        ),
    ]
