# Generated by Django 3.0.3 on 2020-11-17 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_consumables_jig308'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='jig3080',
            field=models.CharField(default=0, max_length=50, verbose_name='Jig AR3080'),
        ),
    ]
