# Generated by Django 3.0.3 on 2020-03-17 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_inventory_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='typemodel',
            field=models.CharField(choices=[('AR15', 'AR15'), ('AR308', 'AR308'), ('TAC9', 'TAC9'), ('80', '80'), ('JIGS', 'JIGS')], default='80', max_length=50),
        ),
    ]
