# Generated by Django 3.0.3 on 2021-01-05 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_addinventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='blemod80',
            field=models.CharField(default=0, max_length=50, verbose_name='Blem OD 80'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='od80',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
