# Generated by Django 3.0.3 on 2020-03-19 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_auto_20200318_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumables',
            name='extendedmagrelease',
            field=models.CharField(default=0, max_length=10),
        ),
    ]
