# Generated by Django 3.0.3 on 2020-03-19 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_consumables_tac9kit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consumables',
            old_name='tac9kit',
            new_name='tac9bufferkit',
        ),
    ]
