# Generated by Django 3.0.3 on 2020-03-30 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FFL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fflnumber', models.CharField(max_length=50, verbose_name='FFL Number')),
                ('fflexp', models.DateField(default='1775/11/10')),
                ('fflimage', models.ImageField(blank=True, upload_to='')),
                ('fflcompanyname', models.CharField(max_length=50, verbose_name='Company Name')),
                ('fflphone', models.CharField(default='none', max_length=50, verbose_name='Phone Number')),
                ('fflemail', models.CharField(default='none', max_length=50, verbose_name='Email')),
                ('fflcontactname', models.CharField(default='none', max_length=50, verbose_name='Contact Name')),
                ('fflmailaddress', models.CharField(max_length=200, verbose_name='Mailing Address')),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'FFL',
                'verbose_name_plural': 'FFLs',
            },
        ),
    ]
