# Generated by Django 3.0.3 on 2020-03-31 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ffl', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ffl',
            name='fflimage',
            field=models.ImageField(blank=True, upload_to='media'),
        ),
        migrations.AlterField(
            model_name='ffl',
            name='fflmailaddress',
            field=models.CharField(max_length=200, verbose_name='Premise Address'),
        ),
    ]
