# Generated by Django 3.0.3 on 2020-03-31 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ffl', '0003_auto_20200331_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ffl',
            name='fflimage',
            field=models.ImageField(blank=True, upload_to='pic_folder/%Y,%m/,%D/', verbose_name='FFL Picture'),
        ),
    ]
