# Generated by Django 3.0.3 on 2020-04-01 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ffl', '0005_auto_20200401_0915'),
    ]

    operations = [
        migrations.AddField(
            model_name='ffl',
            name='fflcfd',
            field=models.CharField(default='none', max_length=50, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='ffl',
            name='fflcity',
            field=models.CharField(default='none', max_length=50, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='ffl',
            name='fflstate',
            field=models.CharField(default='none', max_length=50, verbose_name='State'),
        ),
        migrations.AddField(
            model_name='ffl',
            name='fflzipcode',
            field=models.CharField(default='none', max_length=50, verbose_name='Zipcode'),
        ),
    ]
