# Generated by Django 3.0.3 on 2020-04-01 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ffl', '0006_auto_20200401_0916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ffl',
            name='fflexp',
            field=models.CharField(default='2020-01-01', max_length=50, verbose_name='FFL Exp Date xxxx-xx-xx'),
        ),
    ]
