# Generated by Django 3.0.3 on 2020-04-01 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ffl', '0009_auto_20200401_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ffl',
            name='ffldontship',
            field=models.BooleanField(default=False, verbose_name='FFL doesnt accept shipments'),
        ),
        migrations.AlterField(
            model_name='ffl',
            name='fflshiptomail',
            field=models.BooleanField(default=False, verbose_name='FFL request we use mailing address'),
        ),
    ]
