# Generated by Django 3.0.3 on 2020-04-01 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ffl', '0010_auto_20200401_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ffl',
            name='fflcfd',
            field=models.CharField(default='none', max_length=100, verbose_name='CFD'),
        ),
    ]
